spring:
    mail:
        host: smtp.gmail.com
        password: ${GMAIL_APP_PASSWORD}
        port: 587
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
        username: ${GMAIL_USERNAME}
